### ISSUE TITLE
matrix_ops subject

### ISSUE THREAD

**Issue by nater6** [01-edu/public#1830] opened 2023-02-28 14:11 UTC
matrix_ops
---

There is no indication in the files to submit section that a matrix_ops library ( "matrip_ops/src/lib.rs" and "matrip_ops/cargo.toml")  needs to be submitted as well as "matrix/src/ops.rs"

**Comment by mikysett** [comment] 2023-03-01 14:56
Duplicate of #1826

**Comment by eslopfer** [comment] 2023-03-20 10:33
I am closing this since it was solved in the PR attached to Issue #1826 :+1: 

Thanks Nate for the feedback :slightly_smiling_face:

**Closed by eslopfer** 2023-03-20 10:33 UTC
