### ISSUE TITLE
Ascii-Art-Web

### ISSUE THREAD

**Issue by nsym-coding** [01-edu/public#900] opened 2021-12-07 13:35 UTC
Can we get clarification on what the exact requirements are for the task in terms of the output?

Does everything need to take place on one page only or can it be sent to another page i.e we use / for the get request and then /ascii-art for the post but do they all need to be on one page or can they be on multiple pages?

Cheers

**Comment by LEEDASILVA** [comment] 2021-12-14 17:03
solved in this PR https://github.com/01-edu/public/pull/904

**Comment by sanji-o** [comment] 2022-01-03 19:23
Still unclear to be honest...

I dont think the PR touched the base [ascii-web instructions](https://github.com/01-edu/public/commits/master/subjects/ascii-art-web/README.md)..

**Comment by HanaAbdi** [comment] 2022-01-13 10:09
"ASCII art web, in the audit they ask you two write 123 and hello world with hello world in a new line
But it’s not written anywhere in the intra that we need to do that"
"Yonas asked for clarification as the instructions are a bit vague. 
He opened an issue on the 01 repo but I don’t think it was addressed."

**Comment by Frenchris** [comment] 2022-01-13 10:11
![precise](https://user-images.githubusercontent.com/34804391/149310327-27866193-abf4-4ec8-b477-c8cf3bf992e9.png)

**Comment by LEEDASILVA** [comment] 2022-01-13 10:22
so the first description of the error was a bit unclear so i fixed the export file thinking it was the issue here. Issues must be well described so we can fix it.

For the issue about the new lines not being addressed in the subject, it is by default like this. Since `ascii-art-web` is a project followed by `ascii-art` we wanted the student to try and think about the `ascii-art` project (all possibilities on the `ascii-art`. including the new line) like said in the subject  **` in which it will be possible to use a web **GUI** (graphical user interface) version of your last project, ascii-art`**.

**Comment by LEEDASILVA** [comment] 2022-01-13 10:28
will open a new PR with the following corrections:

-  a more clear explanation on the server routes and the pages

not sure about the last issue about the `123 hello world` which i think it is clear in the subject **` in which it will be possible to use a web **GUI** (graphical user interface) version of your last project, ascii-art`** 

let me know what you think? if it should are not be included

**Comment by MSilva95** [comment] 2022-01-13 11:11
Hello @sanji-o !

Basically what @LEEDASILVA  is saying is that in the first project, ascii-art, it is mandatory for the students to make the program accept the "\n", as we indicated in the subject of that same project.

And since it's asked in the subject of this project, ascii-art-web, to follow the ascii-art project, we don't feel the need to explain the rules again.

"Ascii-art-web consists in creating and running a server, in which it will be possible to use the web **GUI** (graphical user interface) version of your last project, ascii-art."

**Comment by nsym-coding** [comment] 2022-01-26 12:12
Hi guys, 

Sorry my question was just regarding whether ascii-art-web had to all be on one web page or it could have been on multiple web pages etc as there was some confusion amongst us.

Many Thanks

Yonas

**Comment by nik-don** [comment] 2022-01-26 18:06
I believe this is what @nsym-coding and @sanji-o want to know.
(confirmed with nsym in person)

![Screenshot from 2022-01-26 17-50-28](https://user-images.githubusercontent.com/93073558/151220625-ffd63f8c-d3e4-44f2-b118-21813bbe521d.png)

I can see by looking at how most students have done the project that they are using a form with method POST to move into the ascii-art page.

**Comment by LEEDASILVA** [comment] 2022-01-27 15:05
Yes the graphic is pretty good :) i agree with @kigiri. Both are acceptable, maybe we can add some clarification on the subject about that.

**Closed** 2022-02-01 10:00 UTC
