### ISSUE TITLE
Too specific questions in audit lem-in

### ISSUE THREAD

**Issue by October45** [01-edu/public#1636] opened 2022-12-08 08:37 UTC
# Problem

The audit questions are too specific in the lem-in exercise, needing the same amount of turns if interpreted literally.

# How it was found

The example02 provides two solutions:
1. Sending all the ants in one turn on the "start" to "end" link, as there's no restriction of it in the exercise instructions.
2. Sending one ant at a time through the "start"-"end" link, while also using the other path.

During the execution of the exercise I completed the exercise on all points except for examples like example02, which did not fit with my logic. My logic gave 12 turns despite whatever I tried, instead of the intended and needed 11 turns according to the audit.

I kept trying for hours, but then read through the exercise word by word as my solution of "all ants at a time" was validated by another 01 student's lem-in project, and it SHOULD be valid according to the "vagueness" of tunnel/link definition in the exercise instructions.

# Proposed solution

I've created a pull request #1635 with my proposed solution. I just added an "or less" on each question that specifies number of turns, if there's a more efficient solution than the one given in the audit.

I also proposed a change of adding the number of turns in the result of the audit question to ease auditing by not having to count them to compare to a students solution.

**Comment by mikysett** [comment] 2022-12-10 00:46
Thanks a lot for all the details and to have dedicated your time to suggest changes and make me able to better understand the issue.

Let's go in order:
- I've modified the questions to include the number of turns (nice suggestion).
- The questions now state "at most x turns" even if in all cases I've tested the given solution is the optimal one.
- Concerning `example02`:
  - It is achievable in 11 turns as in the example, if your logic gives 12 turns there is probably something to improve on start or end conditions (since it seems you are only losing one step on the road).
  - I understand the suggestion of having all ants moving at once when `start` and `end` are directly linked. Still implemented that way we miss interesting scenarios in terms of path finding and all the maps with this condition will become uninteresting. 
  - To clarify what would be the expected behavior now in the subject and audit it is explicitly stated that "each tunnel can only be used once per turn".
- Thanks a lot for having opened a pull request, actually I've closed it without merging because in the new PR I've modified also the subject and reviewed some other little things.

Some suggestions:
To properly test this exercise is quite tricky, it would be better to use a visualizer that you know is reliable (even better if you can program your own) or at least to take paper and pen and reproduce the graph and the steps. Counting the number of turns is not enough, in that sense giving the number of turns in the question doesn't faster things much.

**Closed** 2022-12-13 16:15 UTC
