### ISSUE TITLE
events subject

### ISSUE THREAD

**Issue by mikkadler** [01-edu/public#2584] opened 2024-05-28 11:10 UTC
events
---
error: package `colored v2.1.0` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.68.2
Either upgrade to rustc 1.70 or newer, or use
cargo update -p colored@2.1.0 --precise ver
where `ver` is the latest version of `colored` supporting rustc 1.68.2

This error seems to originate from the events_test side and how the Cargo.toml is defined there.
Please update rust version or update toml file to include proper version of colored.

**Comment by nprimo** [comment] 2024-05-29 14:18
Hi @mikkadler, thank you for the feedback. I will close this issue since it's a duplicate of [this one](https://github.com/01-edu/public/issues/2583)

**Closed by nprimo** 2024-05-29 14:18 UTC
