### ISSUE TITLE
printalphabet subject

### ISSUE THREAD

**Issue by islam001sko** [01-edu/public#2236] opened 2023-10-04 12:12 UTC
printalphabet
---
Error: Already failed code at commit d69f040

Previous output:
Your program fails (non-zero exit status) when it should not :

$ go run . 
package student/printalphabet is not in GOROOT (/usr/local/go/src/student/printalphabet)
$

Expected :

$ go run . 
abcdefghijklmnopqrstuvwxyz
$

**Comment by mikysett** [comment] 2023-10-06 10:28
Hello @islam001sko 

Thanks for the feedback. First of all may I ask you if you faced the issue in a quest or in an exam?

Also are you the only one concerned or are other learners in the same situation?

If some students passed the exercise may you try and ask to compare your code and git repo structure with theirs?

It seems the issue is on your code and not on the platform, but let me know in any case, with more details I'll be able to check it deeper.

**Comment by mikysett** [comment] 2023-10-09 09:42
I'll close the issue since there is not enough info to take action.

Feel free to write back here and I'll be glad to reopen it :)

**Closed by mikysett** 2023-10-09 09:42 UTC
