### ISSUE TITLE
go-reloaded subject

### ISSUE THREAD

**Issue by SSMM0498** [01-edu/public#1852] opened 2023-03-08 23:50 UTC
go-reloaded
---
In the subject we have this kind of marks '. However in the audit process we have this one ‘

**Comment by davhojt** [comment] 2023-03-09 15:03
@SSMM0498 Which we browser do you use?

**Comment by ololax123** [comment] 2023-03-10 19:18
Seems to be dupe of problem https://github.com/01-edu/public/issues/1515

**Comment by davhojt** [comment] 2023-03-10 21:00
@freeworldwhoo This has been reported before.
Quote character is converted to a speech mark.

**Comment by SSMM0498** [comment] 2023-03-12 13:31
> @SSMM0498 Which we browser do you use?

Edge

**Comment by SSMM0498** [comment] 2023-03-12 13:31
> Seems to be dupe of problem #1515

Yeah it is

**Comment by freeworldwhoo** [comment] 2023-03-16 13:24
Hello @SSMM0498 we are looking into this we will get  back to you as soon as possible

**Closed** 2024-02-01 14:29 UTC
