### ISSUE TITLE
model-selection subject confusing instuctions

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#2330] opened 2023-12-02 08:16 UTC
model-selection
---
A piece of code that should be run preliminary to the task is given for [Exercise 3](https://github.com/01-edu/public/tree/master/subjects/ai/model-selection#exercise-3-gridsearchcv). The code includes creating a `pipeline` which uses `LinearRegression`. However, the following task and the audit questions seem never to use that pipeline. Is that intentional or should we try to somehow implement the pipeline into the process ourselves?

**Comment by MSilva95** [comment] 2023-12-04 09:58
Hello @jarmo-seljamaa , For this exercise what i took from it is that the pipeline setting with Linear Regression appears as an introductory step to showcase the pipeline construction process. The task itself doesn't use this pipeline intentionally to let the students focus solely on the GridSearchCV with Random Forest without using the constructed pipeline.
Let me know if you have a different opinion so that i try to contact the creator to see if something needs to change. Thank you for the feedback!

**Comment by jarmo-seljamaa** [comment] 2023-12-05 20:12
Why did you close this issue without waiting for my feedback?

If you look at Exercise 2, then this gives a very similar perliminary code. In Exercise 2 this whole code is used, including the `pipeline`. If the pipeline should not be used in Exercise 3, then this part of the code should not be given to students (or at least a comment should be added that this part of the code is there for no reason).

Try to put yourself in the student's perspective. We are trying to solve the exercises with all and only the information that is given in the instructions. So the instructions should be sufficient and not confusing. Giving us a piece of sample code to run usually means in other tasks that this code must be used in some way or another.

This of course resonates on the issue of the extremely low quality of instructions in the whole AI branch.

**Comment by MSilva95** [comment] 2023-12-06 12:08
I closed it because it was waiting for two days and sometimes people don't reply, whenever that happens you are free to reopen the issue.

Regarding the unused code i will do a pr with a new version removing the code section so that is less confusing.

Regarding the branch, this was a branch created from an outside contractor, and it needs a full review from our team, we will do a full swipe on it as soon as possible. 
Thanks for all the feedback!

**Comment by jarmo-seljamaa** [comment] 2023-12-06 19:36
Thank you for this. During the piscine it is not always possible to respond quickly because we struggle with the exercises.

I'm glad to hear you are going to review the branch. I have tried to create tickets whenever I spot errors. But not always because sometimes it's hard to tell what to write in the ticket. [Here](https://github.com/01-edu/public/tree/master/subjects/ai/nlp#exercise-7-bag-of-word-representation) is another example of confusing instructions. Task 2 of Exercise 7 says to `create a DataFrame with documents in rows and dictionary in columns` followed by a 3x3 table. What is this table? Is this the expected output? We have 500 columns, should we drop all but 3? 

Only by looking at the audit questions I realize that this 3x3 table must be a small sample of the expected output, but we shouldn't be looking at audit questions to understand what is the task. Unfortunately most of the tasks in this branch require looking at audit questions before submitting the project, or you will never pass the audits.

**Comment by MSilva95** [comment] 2023-12-07 09:50
Hello @jarmo-seljamaa!
Yes i understand that sometimes its not easy to create tickets, and that's why we are very grateful for all the feedback you are giving!

Regarding those two exercises you just talked, i will take a look at them and try to clear things a bit, i will tag this issue in the pr i create as well, to avoid you having to create a new one.

Again thank you for all the feedback!

**Closed** 2023-12-07 17:27 UTC
