### ISSUE TITLE
cl-camp1 subject

### ISSUE THREAD

**Issue by JacksyJack** [01-edu/public#882] opened 2021-11-01 19:49 UTC
cl-camp1
---
Hi. When I click on the run test button, I get this error:

Error: Get file info failed: Not Found

The .sh file is sitting in my repository. I don't think I git it quite right, but can't tell one mlway or the other! 

Thanks

Jack

**Comment by MSilva95** [comment] 2021-11-10 13:55
Did you check if the file has the correct name?

**Comment by Frenchris** [comment] 2021-11-12 10:39
This was most likely a git issue during the first quest. Not a bug as it is an isolated report. Closing the issue.

**Closed by Frenchris** 2021-11-12 10:39 UTC
